default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: philipbroadway  
  password: 
  host: localhost

development:
  <<: *default
  database: temp_check_web

test:
  <<: *default
  database: temp_check_web_test

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORDs'] %>
